/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boletin25.aplicacion;

import boletin25.Metodos;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ldizbarros
 */
public class PaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaPrincipal
     */
    ArrayList <Integer> listaNumeros = new ArrayList();
    
    public PaginaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jB1 = new javax.swing.JButton();
        jLEtiqueta1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTFNumeros = new javax.swing.JTextField();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jB10 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        jB12 = new javax.swing.JButton();
        jB13 = new javax.swing.JButton();
        jB14 = new javax.swing.JButton();
        jB15 = new javax.swing.JButton();
        jB16 = new javax.swing.JButton();
        jB17 = new javax.swing.JButton();
        jB18 = new javax.swing.JButton();
        jB19 = new javax.swing.JButton();
        jB20 = new javax.swing.JButton();
        jB21 = new javax.swing.JButton();
        jB22 = new javax.swing.JButton();
        jB23 = new javax.swing.JButton();
        jB24 = new javax.swing.JButton();
        jB25 = new javax.swing.JButton();
        jB26 = new javax.swing.JButton();
        jB27 = new javax.swing.JButton();
        jB28 = new javax.swing.JButton();
        jB29 = new javax.swing.JButton();
        jB30 = new javax.swing.JButton();
        jB31 = new javax.swing.JButton();
        jB32 = new javax.swing.JButton();
        jB33 = new javax.swing.JButton();
        jB34 = new javax.swing.JButton();
        jB35 = new javax.swing.JButton();
        jB36 = new javax.swing.JButton();
        jB37 = new javax.swing.JButton();
        jB38 = new javax.swing.JButton();
        jB39 = new javax.swing.JButton();
        jB40 = new javax.swing.JButton();
        jB41 = new javax.swing.JButton();
        jB42 = new javax.swing.JButton();
        jB43 = new javax.swing.JButton();
        jB44 = new javax.swing.JButton();
        jB45 = new javax.swing.JButton();
        jB46 = new javax.swing.JButton();
        jB47 = new javax.swing.JButton();
        jB48 = new javax.swing.JButton();
        jB49 = new javax.swing.JButton();
        jBComprobar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BONOLOTO");

        jB1.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB1.setText("1");
        jB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB1ActionPerformed(evt);
            }
        });

        jLEtiqueta1.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jLEtiqueta1.setText("Bonoloto");

        jTFNumeros.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N

        jB2.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB2.setText("2");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jB3.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB3.setText("3");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jB4.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB4.setText("4");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jB5.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB5.setText("5");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB6.setText("6");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jB7.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB7.setText("7");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jB8.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB8.setText("8");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB9.setText("9");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jB10.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB10.setText("10");
        jB10.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB10ActionPerformed(evt);
            }
        });

        jB11.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB11.setText("11");
        jB11.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB11ActionPerformed(evt);
            }
        });

        jB12.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB12.setText("12");
        jB12.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB12ActionPerformed(evt);
            }
        });

        jB13.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB13.setText("13");
        jB13.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB13ActionPerformed(evt);
            }
        });

        jB14.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB14.setText("14");
        jB14.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB14ActionPerformed(evt);
            }
        });

        jB15.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB15.setText("15");
        jB15.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB15ActionPerformed(evt);
            }
        });

        jB16.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB16.setText("16");
        jB16.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB16ActionPerformed(evt);
            }
        });

        jB17.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB17.setText("17");
        jB17.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB17ActionPerformed(evt);
            }
        });

        jB18.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB18.setText("18");
        jB18.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB18ActionPerformed(evt);
            }
        });

        jB19.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB19.setText("19");
        jB19.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB19ActionPerformed(evt);
            }
        });

        jB20.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB20.setText("20");
        jB20.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB20ActionPerformed(evt);
            }
        });

        jB21.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB21.setText("21");
        jB21.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB21ActionPerformed(evt);
            }
        });

        jB22.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB22.setText("22");
        jB22.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB22ActionPerformed(evt);
            }
        });

        jB23.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB23.setText("23");
        jB23.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB23.setMaximumSize(new java.awt.Dimension(48, 38));
        jB23.setMinimumSize(new java.awt.Dimension(48, 38));
        jB23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB23ActionPerformed(evt);
            }
        });

        jB24.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB24.setText("24");
        jB24.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB24ActionPerformed(evt);
            }
        });

        jB25.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB25.setText("25");
        jB25.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB25ActionPerformed(evt);
            }
        });

        jB26.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB26.setText("26");
        jB26.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB26ActionPerformed(evt);
            }
        });

        jB27.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB27.setText("27");
        jB27.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB27ActionPerformed(evt);
            }
        });

        jB28.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB28.setText("28");
        jB28.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB28ActionPerformed(evt);
            }
        });

        jB29.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB29.setText("29");
        jB29.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB29ActionPerformed(evt);
            }
        });

        jB30.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB30.setText("30");
        jB30.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB30ActionPerformed(evt);
            }
        });

        jB31.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB31.setText("31");
        jB31.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB31ActionPerformed(evt);
            }
        });

        jB32.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB32.setText("32");
        jB32.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB32.setMaximumSize(new java.awt.Dimension(48, 38));
        jB32.setMinimumSize(new java.awt.Dimension(48, 38));
        jB32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB32ActionPerformed(evt);
            }
        });

        jB33.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB33.setText("33");
        jB33.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB33ActionPerformed(evt);
            }
        });

        jB34.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB34.setText("34");
        jB34.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB34ActionPerformed(evt);
            }
        });

        jB35.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB35.setText("35");
        jB35.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB35ActionPerformed(evt);
            }
        });

        jB36.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB36.setText("36");
        jB36.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB36ActionPerformed(evt);
            }
        });

        jB37.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB37.setText("37");
        jB37.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB37ActionPerformed(evt);
            }
        });

        jB38.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB38.setText("38");
        jB38.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB38ActionPerformed(evt);
            }
        });

        jB39.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB39.setText("39");
        jB39.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB39ActionPerformed(evt);
            }
        });

        jB40.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB40.setText("40");
        jB40.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB40ActionPerformed(evt);
            }
        });

        jB41.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB41.setText("41");
        jB41.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB41ActionPerformed(evt);
            }
        });

        jB42.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB42.setText("42");
        jB42.setToolTipText("");
        jB42.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB42ActionPerformed(evt);
            }
        });

        jB43.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB43.setText("43");
        jB43.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB43ActionPerformed(evt);
            }
        });

        jB44.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB44.setText("44");
        jB44.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB44ActionPerformed(evt);
            }
        });

        jB45.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB45.setText("45");
        jB45.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB45ActionPerformed(evt);
            }
        });

        jB46.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB46.setText("46");
        jB46.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB46ActionPerformed(evt);
            }
        });

        jB47.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB47.setText("47");
        jB47.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB47ActionPerformed(evt);
            }
        });

        jB48.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB48.setText("48");
        jB48.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB48ActionPerformed(evt);
            }
        });

        jB49.setFont(new java.awt.Font("Ubuntu Light", 1, 24)); // NOI18N
        jB49.setText("49");
        jB49.setMargin(new java.awt.Insets(2, 5, 2, 5));
        jB49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB49ActionPerformed(evt);
            }
        });

        jBComprobar.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jBComprobar.setText("COMPROBAR");
        jBComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBComprobarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(132, 132, 132)
                                                        .addComponent(jB24))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jB15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jB16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jB17)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jB25, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jB18, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jB19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jB26)
                                                        .addGap(6, 6, 6))))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jB8)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB9)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jB1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jB5)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jB29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jB22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jB23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jB30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jB31)
                                                .addGap(18, 18, 18)
                                                .addComponent(jB32, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(22, 22, 22)
                                                .addComponent(jB33)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jB13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB34)
                                            .addComponent(jB6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jB14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jB43, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(jB36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jB37, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                            .addComponent(jB44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jB45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jB38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jB39)
                                                .addGap(24, 24, 24)
                                                .addComponent(jB40, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jB41)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jB42))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jB46)
                                                .addGap(24, 24, 24)
                                                .addComponent(jB47)
                                                .addGap(18, 18, 18)
                                                .addComponent(jB48)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jB49))))
                                    .addComponent(jBComprobar, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLEtiqueta1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLEtiqueta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB1)
                    .addComponent(jB2)
                    .addComponent(jB3)
                    .addComponent(jB4)
                    .addComponent(jB5)
                    .addComponent(jB6)
                    .addComponent(jB7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jB10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jB8)
                        .addComponent(jB9)
                        .addComponent(jB14)
                        .addComponent(jB13)
                        .addComponent(jB12)
                        .addComponent(jB11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB15)
                    .addComponent(jB16)
                    .addComponent(jB17)
                    .addComponent(jB18)
                    .addComponent(jB19)
                    .addComponent(jB20)
                    .addComponent(jB21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB22)
                    .addComponent(jB28)
                    .addComponent(jB27)
                    .addComponent(jB26)
                    .addComponent(jB25)
                    .addComponent(jB24)
                    .addComponent(jB23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB29)
                    .addComponent(jB30)
                    .addComponent(jB31)
                    .addComponent(jB32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB33)
                    .addComponent(jB34)
                    .addComponent(jB35))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB36)
                    .addComponent(jB37)
                    .addComponent(jB38)
                    .addComponent(jB39)
                    .addComponent(jB40)
                    .addComponent(jB41)
                    .addComponent(jB42))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB43)
                    .addComponent(jB44)
                    .addComponent(jB45)
                    .addComponent(jB46)
                    .addComponent(jB47)
                    .addComponent(jB48)
                    .addComponent(jB49))
                .addGap(27, 27, 27)
                .addComponent(jTFNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBComprobar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB1ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB1.getText());
            listaNumeros.add(Integer.parseInt(jB1.getText()));
        }
    }//GEN-LAST:event_jB1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
                if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB2.getText());
            listaNumeros.add(Integer.parseInt(jB2.getText()));
        }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB3.getText());
            listaNumeros.add(Integer.parseInt(jB3.getText()));
        }
    }//GEN-LAST:event_jB3ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB4.getText());
            listaNumeros.add(Integer.parseInt(jB4.getText()));
        }
    }//GEN-LAST:event_jB4ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB5.getText());
            listaNumeros.add(Integer.parseInt(jB5.getText()));
        }
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB6.getText());
            listaNumeros.add(Integer.parseInt(jB6.getText()));
        }
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB7.getText());
            listaNumeros.add(Integer.parseInt(jB7.getText()));
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB8.getText());
            listaNumeros.add(Integer.parseInt(jB8.getText()));
        }
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB9.getText());
            listaNumeros.add(Integer.parseInt(jB9.getText()));
        }
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB10ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB10.getText());
            listaNumeros.add(Integer.parseInt(jB10.getText()));
        }
    }//GEN-LAST:event_jB10ActionPerformed

    private void jB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB11ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB11.getText());
            listaNumeros.add(Integer.parseInt(jB11.getText()));
        }
    }//GEN-LAST:event_jB11ActionPerformed

    private void jB12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB12ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB12.getText());
            listaNumeros.add(Integer.parseInt(jB12.getText()));
        }
    }//GEN-LAST:event_jB12ActionPerformed

    private void jB13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB13ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB13.getText());
            listaNumeros.add(Integer.parseInt(jB13.getText()));
        }
    }//GEN-LAST:event_jB13ActionPerformed

    private void jB14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB14ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB14.getText());
            listaNumeros.add(Integer.parseInt(jB14.getText()));
        }
    }//GEN-LAST:event_jB14ActionPerformed

    private void jB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB15ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB15.getText());
            listaNumeros.add(Integer.parseInt(jB15.getText()));
        }
    }//GEN-LAST:event_jB15ActionPerformed

    private void jB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB16ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB16.getText());
            listaNumeros.add(Integer.parseInt(jB16.getText()));
        }
    }//GEN-LAST:event_jB16ActionPerformed

    private void jB17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB17ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB17.getText());
            listaNumeros.add(Integer.parseInt(jB17.getText()));
        }
    }//GEN-LAST:event_jB17ActionPerformed

    private void jB18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB18ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB18.getText());
            listaNumeros.add(Integer.parseInt(jB18.getText()));
        }
    }//GEN-LAST:event_jB18ActionPerformed

    private void jB19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB19ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB19.getText());
            listaNumeros.add(Integer.parseInt(jB19.getText()));
        }
    }//GEN-LAST:event_jB19ActionPerformed

    private void jB20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB20ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB20.getText());
            listaNumeros.add(Integer.parseInt(jB20.getText()));
        }
    }//GEN-LAST:event_jB20ActionPerformed

    private void jB21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB21ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB21.getText());
            listaNumeros.add(Integer.parseInt(jB21.getText()));
        }
    }//GEN-LAST:event_jB21ActionPerformed

    private void jB22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB22ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB22.getText());
            listaNumeros.add(Integer.parseInt(jB22.getText()));
        }
    }//GEN-LAST:event_jB22ActionPerformed

    private void jB23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB23ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB23.getText());
            listaNumeros.add(Integer.parseInt(jB23.getText()));
        }
    }//GEN-LAST:event_jB23ActionPerformed

    private void jB24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB24ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB24.getText());
            listaNumeros.add(Integer.parseInt(jB24.getText()));
        }
    }//GEN-LAST:event_jB24ActionPerformed

    private void jB25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB25ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB25.getText());
            listaNumeros.add(Integer.parseInt(jB25.getText()));
        }
    }//GEN-LAST:event_jB25ActionPerformed

    private void jB26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB26ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB26.getText());
            listaNumeros.add(Integer.parseInt(jB26.getText()));
        }
    }//GEN-LAST:event_jB26ActionPerformed

    private void jB27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB27ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB27.getText());
            listaNumeros.add(Integer.parseInt(jB27.getText()));
        }
    }//GEN-LAST:event_jB27ActionPerformed

    private void jB28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB28ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB28.getText());
            listaNumeros.add(Integer.parseInt(jB28.getText()));
        }
    }//GEN-LAST:event_jB28ActionPerformed

    private void jB29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB29ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB29.getText());
            listaNumeros.add(Integer.parseInt(jB29.getText()));
        }
    }//GEN-LAST:event_jB29ActionPerformed

    private void jB30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB30ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB30.getText());
            listaNumeros.add(Integer.parseInt(jB30.getText()));
        }
    }//GEN-LAST:event_jB30ActionPerformed

    private void jB31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB31ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB31.getText());
            listaNumeros.add(Integer.parseInt(jB31.getText()));
        }
    }//GEN-LAST:event_jB31ActionPerformed

    private void jB32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB32ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB32.getText());
            listaNumeros.add(Integer.parseInt(jB32.getText()));
        }
    }//GEN-LAST:event_jB32ActionPerformed

    private void jB33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB33ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB33.getText());
            listaNumeros.add(Integer.parseInt(jB33.getText()));
        }
    }//GEN-LAST:event_jB33ActionPerformed

    private void jB34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB34ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB34.getText());
            listaNumeros.add(Integer.parseInt(jB34.getText()));
        }
    }//GEN-LAST:event_jB34ActionPerformed

    private void jB35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB35ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB35.getText());
            listaNumeros.add(Integer.parseInt(jB35.getText()));
        }
    }//GEN-LAST:event_jB35ActionPerformed

    private void jB36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB36ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB36.getText());
            listaNumeros.add(Integer.parseInt(jB36.getText()));
        }
    }//GEN-LAST:event_jB36ActionPerformed

    private void jB37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB37ActionPerformed
        
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            listaNumeros.add(Integer.parseInt(jB37.getText()));
        }
    }//GEN-LAST:event_jB37ActionPerformed

    private void jB38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB38ActionPerformed
        jTFNumeros.setText(jTFNumeros.getText()+" "+jB38.getText());
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
            jTFNumeros.setText(jTFNumeros.getText()+" "+jB37.getText());
            listaNumeros.add(Integer.parseInt(jB38.getText()));
        }
    }//GEN-LAST:event_jB38ActionPerformed

    private void jB39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB39ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB39.getText());
            listaNumeros.add(Integer.parseInt(jB39.getText()));
        }
    }//GEN-LAST:event_jB39ActionPerformed

    private void jB40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB40ActionPerformed
      
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
              jTFNumeros.setText(jTFNumeros.getText()+" "+jB40.getText());
            listaNumeros.add(Integer.parseInt(jB40.getText()));
        }
    }//GEN-LAST:event_jB40ActionPerformed

    private void jB41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB41ActionPerformed
     
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
               jTFNumeros.setText(jTFNumeros.getText()+" "+jB41.getText());
            listaNumeros.add(Integer.parseInt(jB41.getText()));
        }
    }//GEN-LAST:event_jB41ActionPerformed

    private void jB42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB42ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB42.getText());
            listaNumeros.add(Integer.parseInt(jB42.getText()));
        }
    }//GEN-LAST:event_jB42ActionPerformed

    private void jB43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB43ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB43.getText());
            listaNumeros.add(Integer.parseInt(jB43.getText()));
        }
    }//GEN-LAST:event_jB43ActionPerformed

    private void jB44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB44ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB44.getText());
            listaNumeros.add(Integer.parseInt(jB44.getText()));
        }
    }//GEN-LAST:event_jB44ActionPerformed

    private void jB45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB45ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB45.getText());
            listaNumeros.add(Integer.parseInt(jB45.getText()));
        }
    }//GEN-LAST:event_jB45ActionPerformed

    private void jB46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB46ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB46.getText());
            listaNumeros.add(Integer.parseInt(jB46.getText()));
        }
    }//GEN-LAST:event_jB46ActionPerformed

    private void jB47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB47ActionPerformed
       
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB47.getText());
            listaNumeros.add(Integer.parseInt(jB47.getText()));
        }
    }//GEN-LAST:event_jB47ActionPerformed

    private void jB48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB48ActionPerformed
      
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
              jTFNumeros.setText(jTFNumeros.getText()+" "+jB48.getText());
            listaNumeros.add(Integer.parseInt(jB48.getText()));
        }
    }//GEN-LAST:event_jB48ActionPerformed

    private void jB49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB49ActionPerformed
        if (listaNumeros.size()==6){
            JOptionPane.showMessageDialog(rootPane, "Ya has introducido los 6 digitos");
        }else{
             jTFNumeros.setText(jTFNumeros.getText()+" "+jB49.getText());
            listaNumeros.add(Integer.parseInt(jB49.getText()));
        }
    }//GEN-LAST:event_jB49ActionPerformed

    private void jBComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBComprobarActionPerformed
        if (listaNumeros.size()<6){
            JOptionPane.showMessageDialog(rootPane, "No has introducido 6 numeros! Introduce mas para continuar");
        }else{
            Metodos.comprobar(listaNumeros);
            listaNumeros.clear();
             jTFNumeros.setText("");
        }
    }//GEN-LAST:event_jBComprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB10;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB12;
    private javax.swing.JButton jB13;
    private javax.swing.JButton jB14;
    private javax.swing.JButton jB15;
    private javax.swing.JButton jB16;
    private javax.swing.JButton jB17;
    private javax.swing.JButton jB18;
    private javax.swing.JButton jB19;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB20;
    private javax.swing.JButton jB21;
    private javax.swing.JButton jB22;
    private javax.swing.JButton jB23;
    private javax.swing.JButton jB24;
    private javax.swing.JButton jB25;
    private javax.swing.JButton jB26;
    private javax.swing.JButton jB27;
    private javax.swing.JButton jB28;
    private javax.swing.JButton jB29;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB30;
    private javax.swing.JButton jB31;
    private javax.swing.JButton jB32;
    private javax.swing.JButton jB33;
    private javax.swing.JButton jB34;
    private javax.swing.JButton jB35;
    private javax.swing.JButton jB36;
    private javax.swing.JButton jB37;
    private javax.swing.JButton jB38;
    private javax.swing.JButton jB39;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB40;
    private javax.swing.JButton jB41;
    private javax.swing.JButton jB42;
    private javax.swing.JButton jB43;
    private javax.swing.JButton jB44;
    private javax.swing.JButton jB45;
    private javax.swing.JButton jB46;
    private javax.swing.JButton jB47;
    private javax.swing.JButton jB48;
    private javax.swing.JButton jB49;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBComprobar;
    private javax.swing.JLabel jLEtiqueta1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFNumeros;
    // End of variables declaration//GEN-END:variables
}
